### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by frankshearar** [blumu/ResumableMonad#1]
I would love to see this package published to NuGet!

**Comment by frankshearar** [comment]
Ignore me. I mistook the documentation for a framework into which I could simply plug in things like how to "checkpoint" the computation. Instead, this project describes the resumable monad itself.

**Comment by blumu** [comment]
@frankshearar No problem. I do plan do release a library based on this work at some point. I will make sure to release it on Nuget when this happens.
